config/routes.rb
Diagnose::Application.routes.draw do

devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}, path_names: { sign_in: 'login', sign_out: 'logout' }

  
  resources :latex
  ActiveAdmin.routes(self)
  resources :categories
  
  controller 'diagnoses' do
    get 'diagnoses/mathe' => 'diagnoses#math'
    get 'diagnoses/chemie' => 'diagnoses#chemistry'
  end

  resources :diagnoses do
    collection do
      get 'diagnosed'
      post 'create'
      get 'index'
    end
  end

  
  controller 'questions' do
    get 'questions/mathe' => 'questions#math'
    get 'questions/chemie' => 'questions#chemistry'
  end

  resources :questions
  

resources :mains

  root 'diagnoses#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
resourcify
belongs_to :category, :foreign_key => 'category_id'
validates :title, :presence => true
validates :content , :presence => true
validates :right , :presence => true
validates :category , :presence => true
validates :exercise , :presence => true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy], except: [:math, :chemistry]
  before_filter :authenticate_user!
  #rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  
  layout 'wide'

  # GET /questions
  # GET /questions.json
  def index


    @question = Question.all

    @category = Category.all
  end

  def math
    @maths= Question.joins(:category).where("categories.title = ?", "Mathematik")

  end

  def chemistry
    @chemistries= Question.joins(:category).where("categories.title = ?", "Chemie")

  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
   @question = Question.new
   @category = Category.all 
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
 
    @category = Category.all
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :number, :content, :answer1, :answer2, :answer3, :answer4, :right, :category_id, :exercise )
    end

#   def record_not_found
#     redirect_to action: :index
#   end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.haml
= simple_form_for @question do |f|
  = f.input :title , :input_html => {:style=> 'width: 300px'}, label: 'Themengebiet oder Unterthema'
  = f.association :category, include_blank: false ,:input_html => {:style=> 'width: 300px'}
  = f.input :number , :input_html => {:style=> 'width: 300px'}, label: 'Checklistennummer?'
  = f.input :content ,:input_html => {:style=> 'width: 500px'}, label: 'Frage'
  = f.input :answer1 ,:input_html => {:style=> 'width: 400px'}, label: 'Antwort 1'
  = f.input :answer2, :input_html => {:style=> 'width: 400px'}, label: 'Antwort 2'
  = f.input :answer3, :input_html => {:style=> 'width: 400px'}, label: 'Antwort 3'
  = f.input :answer4, :input_html => {:style=> 'width: 400px'}, label: 'Antwort 4'
  = f.input :right ,label: 'Welche Antwortnummer ist richtig?',:input_html => {:maxlength =>1,:style=> 'width: 50px'}
  = f.input :exercise, :input_html => {:style=> 'width: 400px; height: 100px'}, label: 'Latex-Übung/Hilfe'
  = f.button :submit

app/views/questions/chemistry.html.haml
%h1 Chemistry questions
%table
  %thead
    %tr
      %th Kategorie
      %th Title
      %th Number
      %th Content
      %th Answer1
      %th Answer2
      %th Answer3
      %th Answer4
      %th Right
      %th
      %th
      %th
  %tbody
    - @chemistries.each do |q|
      %tr
        %td= q.category.title
        %td= q.title
        %td= q.number
        %td= q.content
        %td= q.answer1
        %td= q.answer2
        %td= q.answer3
        %td= q.answer4
        %td= q.right
        %td= link_to 'Show', q
        %td= link_to 'Edit', edit_question_path(q)
        %td= link_to 'Destroy', q, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Question', new_question_path

app/views/questions/edit.html.haml
%h1 Editing question
= render 'form'
= link_to 'Show', @question
|
\#{link_to 'Back', questions_path}

app/views/questions/index.html.haml
%h1 Listing questions
%table
  %thead
    %tr
      %th Kategorie
      %th Title
      %th Number
      %th Content
      %th Answer1
      %th Answer2
      %th Answer3
      %th Answer4
      %th Right
      %th Latex-Übung
      %th
      %th
      %th
  %tbody
    - @question.each do |q|
      %tr
        %td= q.category.title
        %td= q.title
        %td= q.number
        %td= q.content
        %td= q.answer1
        %td= q.answer2
        %td= q.answer3
        %td= q.answer4
        %td= q.right
        %td= q.exercise
        %td= link_to 'Show', q
        %td= link_to 'Edit', edit_question_path(q)
        %td= link_to 'Destroy', q, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Question', new_question_path

app/views/questions/math.html.haml
%h1 Math questions
%table
  %thead
    %tr
      %th Kategorie
      %th Title
      %th Number
      %th Content
      %th Answer1
      %th Answer2
      %th Answer3
      %th Answer4
      %th Right
      %th
      %th
      %th
  %tbody
    - @maths.each do |q|
      %tr
        %td= q.category.title
        %td= q.title
        %td= q.number
        %td= q.content
        %td= q.answer1
        %td= q.answer2
        %td= q.answer3
        %td= q.answer4
        %td= q.right
        %td= link_to 'Show', q
        %td= link_to 'Edit', edit_question_path(q)
        %td= link_to 'Destroy', q, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question
= render 'form'
= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice
%p
  %strong Category:
  = @question.category.title
%p
  %strong Title:
  = @question.title
%p
  %strong Number:
  = @question.number
%p
  %strong Content:
  = @question.content
%p
  %strong Answer1:
  = @question.answer1
%p
  %strong Answer2:
  = @question.answer2
%p
  %strong Answer3:
  = @question.answer3
%p
  %strong Answer4:
  = @question.answer4
%p
  %strong Right:
  = @question.right
%p
  %strong Exercise:
  = @question.exercise

= link_to 'Edit', edit_question_path(@question)
|
\#{link_to 'Back', questions_path}