config/routes.rb
Diagnose::Application.routes.draw do

devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}, path_names: { sign_in: 'login', sign_out: 'logout' }

  
  resources :latex
  ActiveAdmin.routes(self)
  resources :categories
  
  controller 'diagnoses' do
    get 'diagnoses/mathe' => 'diagnoses#math'
    get 'diagnoses/chemie' => 'diagnoses#chemistry'
  end

  resources :diagnoses do
    collection do
      get 'diagnosed'
      post 'create'
      get 'index'
    end
  end

  
  controller 'questions' do
    get 'questions/mathe' => 'questions#math'
    get 'questions/chemie' => 'questions#chemistry'
  end

  resources :questions
  

resources :mains

  root 'diagnoses#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions, dependent: :destroy

resourcify
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  # there is no model to be looked through
  #before_action :set_diagnosis, except: [:math, :chemistry]

  #rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  # GET /diagnoses
  # GET /diagnoses.json
  def index
    #@questions = Question.all#.sample(2)

   # THIS IS IMPORTANT. Without this, you still get the last checked value when the user come to the index action directly.
	session[:tmp_diagnosis_raw] = nil
	session[:tmp_diagnosis_right] = nil
	session[:tmp_diagnosis_array] = nil


  end

  # GET diagnoses/math picks random questions from "Mathematik"
  def math
    @maths = Question.joins(:category).where("categories.title = ?", "Mathematik").sample(2) 

   # THIS IS IMPORTANT. Without this, you still get the last checked value when the user come to the index action directly.
	session[:tmp_diagnosis_raw] = nil
	session[:tmp_diagnosis_right] = nil
	session[:tmp_diagnosis_array] = nil
  end


  def chemistry
    @chemistries= Question.joins(:category).where("categories.title = ?", "Chemie").sample(2) 

   # THIS IS IMPORTANT. Without this, you still get the last checked value when the user come to the index action directly.
	session[:tmp_diagnosis_raw] = nil
	session[:tmp_diagnosis_right] = nil
	session[:tmp_diagnosis_array] = nil

  end



  def show
  end

  def edit
	
  end



  # POST /diagnoses
  # POST /diagnoses.json
  def create
	#flash[:message] = params[:question_ids]

        # ["1 2", "2 1", "3 2"]


	right = []
        result = []
	array = []
        
        begin
	  params[:question_ids].each do |p|
		result = p.gsub(/\s+/m, ' ').strip.split(" ")
		array << [result[0],result[1]]
		if result[1] == Question.find(result[0].to_i).right.to_s then right << [result[0],result[1]] end
	end

          rescue
            redirect_to(:action => 'index')
          return
        end

	
        if right.empty?
		r = "0" 
	else r = right.size end

        #flash[:message] = "Richtig sind: " + r.to_s #+ params[:question_ids].to_s + "result: " + result.to_s

	session[:tmp_diagnosis_raw] = params[:question_ids]
	session[:tmp_diagnosis_array] = array
	session[:tmp_diagnosis_right] = right
	
  	redirect_to diagnosed_diagnoses_path

        
#        respond_to do |format|
 #     	format.html { redirect_to diagnoses_url }
  #   	format.json { head :no_content }
   # 	end

    
  end


  #GET from form_tag
  def diagnosed

    @questions = Question.all


        @diagnosed_raw = session[:tmp_diagnosis_raw]
	@diagnosed_right_size = session[:tmp_diagnosis_right].size.to_s
	@diagnosed_right = session[:tmp_diagnosis_right]
	@diagnosed_array = session[:tmp_diagnosis_array]

    begin
      ex = nil
      ex = []
      wrong = nil
      wrong = []
      wrong = session[:tmp_diagnosis_array] - session[:tmp_diagnosis_right]
        if wrong.empty? then
          ex = ["Nichts zu üben 1"]
        else
          wrong.each do |e|
          ex << Question.find(e[0][0]).exercise
        end

      end

    rescue
      ex = ["Nichts zu üben 2"]
    end

    session[:tmp_diagnosed_ex] = ""
 
    session[:tmp_diagnosed_ex] = ex.join.to_s

    @diagnosed_exs = session[:tmp_diagnosed_ex]

    @diagnosed_ex = ex


  end


  private
    # Use callbacks to share common setup or constraints between actions.
    #  #### there is no model to be found!
    #def set_diagnosis
    #  #@diagnosis = Diagnosis.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnosis_params
      params[:diagnosis]
    end

# def record_not_found
  #   redirect_to action: :index
  # end

end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/views/diagnoses/_form.html.haml
= form_for(@diagnosis) do |f|
  - if @diagnosis.errors.any?
    #error_explanation
      %h2
        = pluralize(@diagnosis.errors.count, "error")
        prohibited this diagnosis from being saved:
      %ul
        - @diagnosis.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/diagnoses/chemistry.html.haml
%h1 Listing chemistry questions for diagnosis
= flash[:notice]
%br/
= form_tag({:action => :create}, {:method => :post }) do
  %table
    - @chemistries.each do |question|
      %tr
        %td
          = question.content
        %td
          = check_box_tag 'question_ids[]', [question.id,1]
          = question.answer1
        %td
          = check_box_tag 'question_ids[]', [question.id,2]
          = question.answer2
        %td
          = check_box_tag 'question_ids[]', [question.id,3]
          = question.answer3
        %td
          = check_box_tag 'question_ids[]', [question.id,4]
          = question.answer4
  = flash[:message]
  %br/
  = submit_tag("Fertig und möchte eine Auswertung", class: "button", :action => "create" )
%br/
= link_to 'Andere Kategorie wählen', :action => "index"
= link_to 'Neue Zufallsfragen', :action => "chemistry"

app/views/diagnoses/diagnosed.html.haml
%h1 Auswertung der Diagnose
%br/
%h2 So wurde beantwortet:
%table
  %th Fragen Nr.
  %th "Deine" Nr.
  %th Frage 
  %th Richtige Nummer
  %th Richtige Antwort
  - @diagnosed_array.each do |d|
    %tr
      %td.center
        = d[0]
        \.
      %td.center
        = d[1]
        \.
      %td
        = @questions.find(d[0]).content
      %td.green_bold.center
        = @questions.find(d[0]).right.to_s
        \.
      %td.green_bold
        = case @questions.find(d[0]).right.to_s       |
          when "1" then @questions.find(d[0]).answer1 |
          when "2" then @questions.find(d[0]).answer2 |
          when "3" then @questions.find(d[0]).answer3 |
          when "4" then @questions.find(d[0]).answer4 |
          end                                         |
%h2
  Du hast also #{@diagnosed_right_size} richtig.
/ <h2>Array: <haml:loud> @diagnosed_array </haml:loud></h2>
= link_to "Erneut", :action => "index"
%br/
= link_to "Übungsaufgaben drucken", :controller => "latex", :action => "index", :format => :pdf
%br/
%br/
%br/

-#%p 
-#  Raw from form:
-#  = @diagnosed_raw
-#%p 
-#  Array after sorting through:
-#  = @diagnosed_array
-#%p
-#  Right:
-#  = @diagnosed_right
-#%p
-#  Array minus Right:
-#  = @diagnosed_array - @diagnosed_right
-#%p
-#  ex:
-#  - @diagnosed_ex.each do |e|
-#    = e.to_s
-#%p
-#  session diagnosed_ex_s:
-#  = @diagnosed_exs

app/views/diagnoses/edit.html.haml
%h1 Editing diagnosis
= render 'form'
= link_to 'Show', @diagnosis
|
\#{link_to 'Back', diagnoses_path}

app/views/diagnoses/index.html.haml
%br/
%br/
%h1 Diagnose gefällig?
%br/
%br/
= link_to "Zufällige Fragen zur Mathematik", {controller: "diagnoses", action: "math"}, {class: 'button expand'}
%br/
%br/
= link_to "Zufällige Fragen zur Chemie", {controller: "diagnoses", action: "chemistry"}, {class: 'button expand'}
%br/
%br/



-# this below is a huge comment! ##########
- if false
  %h1 Listing math questions for diagnosis
  = flash[:notice]
  %br/
  = form_tag({:action => :create}, {:method => :post }) do
    %table
      - @questions.each do |question|
        %tr
          %td
            = question.content
          %td
            = check_box_tag 'question_ids[]', [question.id,1]
            = question.answer1
          %td
            = check_box_tag 'question_ids[]', [question.id,2]
            = question.answer2
          %td
            = check_box_tag 'question_ids[]', [question.id,3]
            = question.answer3
          %td
            = check_box_tag 'question_ids[]', [question.id,4]
            = question.answer4
    = flash[:message]
    %br/
    = submit_tag("Fertig und möchte eine Auswertung", class: "button")
  %br/

app/views/diagnoses/math.html.haml
%h1 Listing math questions for diagnosis
= flash[:notice]
%br/
= form_tag({:action => :create}, {:method => :post }) do
  %table
    - @maths.each do |question|
      %tr
        %td
          = question.content
        %td
          = check_box_tag 'question_ids[]', [question.id,1]
          = question.answer1
        %td
          = check_box_tag 'question_ids[]', [question.id,2]
          = question.answer2
        %td
          = check_box_tag 'question_ids[]', [question.id,3]
          = question.answer3
        %td
          = check_box_tag 'question_ids[]', [question.id,4]
          = question.answer4
  = flash[:message]
  %br/
  = submit_tag("Fertig und möchte eine Auswertung", class: "button", :action => "create")
%br/
= link_to 'Andere Kategorie wählen', :action => "index"
= link_to 'Neue Zufallsfragen', :action => "math"


%br/

app/views/diagnoses/new.html.haml
%h1 New diagnosis
= render 'form'
= link_to 'Back', diagnoses_path

app/views/diagnoses/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_diagnosis_path(@diagnosis)
|
\#{link_to 'Back', diagnoses_path}