config/routes.rb
Diagnose::Application.routes.draw do

devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}, path_names: { sign_in: 'login', sign_out: 'logout' }

  
  resources :latex
  ActiveAdmin.routes(self)
  resources :categories
  
  controller 'diagnoses' do
    get 'diagnoses/mathe' => 'diagnoses#math'
    get 'diagnoses/chemie' => 'diagnoses#chemistry'
  end

  resources :diagnoses do
    collection do
      get 'diagnosed'
      post 'create'
      get 'index'
    end
  end

  
  controller 'questions' do
    get 'questions/mathe' => 'questions#math'
    get 'questions/chemie' => 'questions#chemistry'
  end

  resources :questions
  

resources :mains

  root 'diagnoses#index'

end

app/models/main.rb
class Main < ActiveRecord::Base

resourcify
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all.order('mains.created_at DESC')


  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: 'Main was successfully created.' }
        format.json { render action: 'show', status: :created, location: @main }
      else
        format.html { render action: 'new' }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1
  # PATCH/PUT /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to @main, notice: 'Main was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def main_params
      params.require(:main).permit(:title, :content)
    end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/mains/_form.html.haml
= form_for(@main) do |f|
  - if @main.errors.any?
    #error_explanation
      %h2
        = pluralize(@main.errors.count, "error")
        prohibited this main from being saved:
      %ul
        - @main.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :content
    %br/
    = f.text_field :content
  .actions
    = f.submit

app/views/mains/edit.html.haml
%h1 Editing main
= render 'form'
= link_to 'Show', @main
|
\#{link_to 'Back', mains_path}

app/views/mains/index.html.haml
%h1 Listing mains
%table
  %thead
    %tr
      %th Title
      %th Content
      %th Createt at
      %th
      %th
      %th
  %tbody
    - @mains.each do |main|
      %tr
        %td= main.title
        %td= main.content
        %td= main.created_at
        %td= link_to 'Show', main
        %td= link_to 'Edit', edit_main_path(main)
        %td= link_to 'Destroy', main, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Main', new_main_path

app/views/mains/new.html.haml
%h1 New main
= render 'form'
= link_to 'Back', mains_path

app/views/mains/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @main.title
%p
  %strong Content:
  = @main.content
= link_to 'Edit', edit_main_path(@main)
|
\#{link_to 'Back', mains_path}